---
- name: Deploy healthcheck script for keepalived
  ansible.builtin.template:
    src: check_haproxy.sh.j2
    dest: /etc/keepalived/check_haproxy.sh
    owner: root
    group: root
    mode: "0755"
  notify: Restart keepalived

- name: Deploy keepalived.conf
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart keepalived

- name: Enable and start keepalived
  ansible.builtin.systemd:
    name: keepalived
    enabled: true
    state: started