kube_vip_enabled: true
kube_vip_arp_enabled: true
kube_vip_controlplane_enabled: true
kube_vip_address: 10.0.30.30
loadbalancer_apiserver:
   address: "{{ kube_vip_address }}"
   port: 6443
kube_vip_services_enabled: false

kube_proxy_strict_arp: true

#kube_network_plugin: calico
#kube_service_addresses: 10.233.0.0/18
#kube_pods_subnet: 10.233.64.0/18
#kube_network_node_prefix: 24
#kube_service_addresses_ipv6: fd85:ee78:d8a6:8607::1000/116
#kube_pods_subnet_ipv6: fd85:ee78:d8a6:8607::1:0000/112
#kube_network_node_prefix_ipv6: 120

kubelet_rotate_server_certificates: true
kubelet_rotate_certificates: true
kubelet_csr_approver_values:
  providerIpPrefixes: [ '10.0.0.0/18' ] # Заміни на свою реальну підмережу нод
  maxExpirationSeconds: 86400
  bypassDnsResolution: true
  bypassHostnameCheck: true